### ISSUE TITLE
The implementation of the negative distributions is wrong

### ISSUE THREAD

**Issue by pberkes** [wichmann-lab/python-psignifit#141]
For example, the value of a negative sigmoid at x, is not `1 - sigmoid(x)`, as in the current code (see below), but `sigmoid(1 - x)` (or else I'm misunderstanding what "negative" is).

In the case of symmetrical sigmoids with threshold = 0.5, they are the same, which is why the tests were passing.

```
    def __call__(self, stimulus_level: N, threshold: N, width: N) -> N:
        """ Calculate the sigmoid value at specified stimulus levels. """
        value = self._value(stimulus_level, threshold, width)

        if self.negative:
            return 1 - value
        else:
            return value
```

**Comment by pberkes** [comment]
I was wrong, negative seems to mean `1 - sigmoid(x)`. Closing

**Comment by pberkes** [comment]
Reopening: one of the reasons I was confused is that in `Sigmoid.__init__` we have 

```
if negative:
    self.PC = 1 - PC
else:
    self.PC = PC
```

which suggests that negative sigmoids are switched along the x-axis (sigmoid(1 - x)) instead of the y-axis (1 - sigmoid(x)).

The current code would make the threshold for the sigmoid below at PC=0.6 to be something like 3, while I expect 6
![telegram-cloud-photo-size-2-5447644065236640566-y](https://github.com/user-attachments/assets/3fcc94e6-569d-4c16-b0d8-b96bc2c3305b)

I think the code is incorrect, and will submit tests to prove it ;-)

**Comment by otizonaizit** [comment]
I think with this kind of things it is important to double check what the MATLAB version is doing.
There are two possible outcomes:

1. MATLAB behaves differently: this indicates that the problem is in the porting, in which case we can just fix things without further ado, or
2. MATLAB is doing the same thing: we should ask @FelixWichmann and @HeikoSchuett if the observed behavior is a bug or a feature, and only then proceed with fixing things

The same argument holds for  #143, #145, #137, #109, and probably others.

In this particular case "negative" sigmoid is probably a field-specific term, so I think it's safer to just ask @FelixWichmann and @HeikoSchuett instead of guessing what it may mean...

**Comment by otizonaizit** [comment]
Of course acting as I describe above is a lot of effort, especially because the APIs are so different that it is not necessarily obvious how to replicate things in MATLAB. On the other hand, I don't see an easier way to approach this issue.

**Comment by guillermoaguilar** [comment]
I don't think the python implementation is wrong actually.

When running the [example data for a negative sigmoid] in the `main` branch it does fit it and gives me the same plot as the MATLAB version  (BTW the plot from above comes from MATLAB).  The MATLAB version returns 0.006 for reading a threshold at 0.55.

What it doesn't work is `result.threshold(0.55)`, but that is because of #139. Now if I use the code that fixes that bug (PR #139), it works fine and  `result.threshold(0.55)` gives me 0.006, as MATLAB. @pberkes can you check if it also works like this for you?

Negative just means negative slope, PC going down from (1-lambda) to gamma as stimulus intensity increases.

**Comment by guillermoaguilar** [comment]
Code with example data:

```
import numpy as np
from psignifit import psignifit
from psignifit import psigniplot
import matplotlib.pyplot as plt

## Example data from 
# https://github.com/wichmann-lab/psignifit/wiki/Negative-Slope-Sigmoids

DATA =np.array([[0.0010,   89.0000,   90.0000],
                [0.0015,   84.0000,   90.0000],
                [0.0020,   90.0000,   90.0000],
                [0.0025,   90.0000,   90.0000],
                [0.0030,   82.0000,   90.0000],
                [0.0035,   81.0000,   90.0000],
                [0.0040,   72.0000,   90.0000],
                [0.0045,   70.0000,   90.0000],
                [0.0050,   58.0000,   90.0000],
                [0.0060,   55.0000,   90.0000],
                [0.0070,   46.0000,   90.0000],
                [0.0080,   44.0000,   90.0000],
                [0.0100,   44.0000,   90.0000]])

if __name__=='__main__':
   
    result = psignifit(DATA, 
                       sigmoid='neg_norm', 
                       CI_method='percentiles',
                       experiment_type='2AFC'
                       )
     
    plt.figure()
    psigniplot.plot_psychometric_function(result)
    plt.show()
    
    print(result.threshold(0.55))
 
```

**Comment by pberkes** [comment]
@guillermoaguilar of course the example works, PC is set to 0.5 , so 1-PC is still 0.5 . Try with 0.4

**Comment by pberkes** [comment]
@otizonaizit I cannot run Matlab code because I don't have the license, but from this file I think it would behave as my fix: https://github.com/wichmann-lab/psignifit/blob/dc8098f2d4da25632ce74db06dffddd3618798da/getThreshold.m#L67

**Comment by pberkes** [comment]
@guillermoaguilar @otizonaizit  ok it's complicated... let's try to sort it out

- One could say that the original version is correct and behaves like Matlab
- But: a negative sigmoid sets its `self.PC` parameter to 1-PC (the PC with which the sigmoid is created). This is a convenience so that one does not need to modify `_value`, `_inverse`, or `_slope`. It's the same trick as in the Matlab version (https://github.com/wichmann-lab/psignifit/blob/dc8098f2d4da25632ce74db06dffddd3618798da/getThreshold.m#L61)
- However: in the Matlab version, it's a temporary trick, the value of the PC parameter is left intact. In the Python code, the value of the PC parameter is permanently modified. This means that any code that uses the `sigmoid.PC` parameter for plotting, or to do computations (as it was the case in the sigmoid tests) will be broken.
- A solution that I propose instead of the change I made in #146: 1) keep `sigmoid.PC` to the value it has when the sigmoid is created; 2) add a private parameter `sigmoid._PC` that is equal to `PC`, or `1 - PC` for negative sigmoids; 2) use `sigmoid._PC` in `_value`, `_inverse`, and `_slope`

**Comment by otizonaizit** [comment]
> @guillermoaguilar @otizonaizit ok it's complicated... let's try to sort it out

thanks for the detailed ananlysis, this sheds a bright light in the issue :-))

>     * A solution that I propose instead of the change I made in [Fix negative sigmoid, improve sigmoid tests #146](https://github.com/wichmann-lab/python-psignifit/pull/146): 1) keep `sigmoid.PC` to the value it has when the sigmoid is created; 2) add a private parameter `sigmoid._PC` that is equal to `PC`, or `1 - PC` for negative sigmoids; 2) use `sigmoid._PC` in `_value`, `_inverse`, and `_slope`

This sound like a very good plan! +1

**Comment by pberkes** [comment]
yes!
